export const mockGames = {
  count: 50,
  next: null,
  previous: null,
  results: [
    {
      id: 1,
      name: "Grand Theft Auto V",
      rating: 4.47,
      released: "2013-09-17",
      background_image: "https://placehold.co/600x800?text=GTA+V",
      genres: ["Action", "Adventure"],
      parent_platforms: ["PC", "PlayStation", "Xbox"],
    },
    {
      id: 2,
      name: "Red Dead Redemption 2",
      rating: 4.66,
      released: "2018-10-26",
      background_image: "https://placehold.co/600x800?text=RDR2",
      genres: ["Action", "Adventure"],
      parent_platforms: ["PC", "PlayStation", "Xbox"],
    },
    {
      id: 3,
      name: "Elden Ring",
      rating: 4.65,
      released: "2022-02-25",
      background_image: "https://placehold.co/600x800?text=Elden+Ring",
      genres: ["Action RPG"],
      parent_platforms: ["PC", "PlayStation", "Xbox"],
    },
    {
      id: 4,
      name: "The Witcher 3: Wild Hunt",
      rating: 4.68,
      released: "2015-05-19",
      background_image: "https://placehold.co/600x800?text=Witcher+3",
      genres: ["RPG"],
      parent_platforms: ["PC", "PlayStation", "Xbox", "Switch"],
    },
    {
      id: 5,
      name: "Cyberpunk 2077",
      rating: 4.32,
      released: "2020-12-10",
      background_image: "https://placehold.co/600x800?text=Cyberpunk+2077",
      genres: ["RPG"],
      parent_platforms: ["PC", "PlayStation", "Xbox"],
    },
    {
      id: 6,
      name: "God of War",
      rating: 4.72,
      released: "2018-04-20",
      background_image: "https://placehold.co/600x800?text=God+of+War",
      genres: ["Action"],
      parent_platforms: ["PC", "PlayStation"],
    },
    {
      id: 7,
      name: "God of War Ragnarök",
      rating: 4.74,
      released: "2022-11-09",
      background_image: "https://placehold.co/600x800?text=Ragnarok",
      genres: ["Action"],
      parent_platforms: ["PlayStation"],
    },
    {
      id: 8,
      name: "Minecraft",
      rating: 4.55,
      released: "2011-11-18",
      background_image: "https://placehold.co/600x800?text=Minecraft",
      genres: ["Sandbox"],
      parent_platforms: ["PC", "PlayStation", "Xbox", "Switch"],
    },
    {
      id: 9,
      name: "Hades",
      rating: 4.61,
      released: "2020-09-17",
      background_image: "https://placehold.co/600x800?text=Hades",
      genres: ["Roguelike"],
      parent_platforms: ["PC", "Switch", "PlayStation", "Xbox"],
    },
    {
      id: 10,
      name: "Hollow Knight",
      rating: 4.7,
      released: "2017-02-24",
      background_image: "https://placehold.co/600x800?text=Hollow+Knight",
      genres: ["Metroidvania"],
      parent_platforms: ["PC", "Switch", "PlayStation", "Xbox"],
    },
    {
      id: 11,
      name: "Baldur's Gate 3",
      rating: 4.82,
      released: "2023-08-03",
      background_image: "https://placehold.co/600x800?text=BG3",
      genres: ["RPG"],
      parent_platforms: ["PC", "PlayStation", "Xbox"],
    },
    {
      id: 12,
      name: "Portal 2",
      rating: 4.63,
      released: "2011-04-19",
      background_image: "https://placehold.co/600x800?text=Portal+2",
      genres: ["Puzzle"],
      parent_platforms: ["PC", "PlayStation", "Xbox"],
    },
    {
      id: 13,
      name: "Half-Life 2",
      rating: 4.6,
      released: "2004-11-16",
      background_image: "https://placehold.co/600x800?text=Half-Life+2",
      genres: ["Shooter"],
      parent_platforms: ["PC"],
    },
    {
      id: 14,
      name: "DOOM Eternal",
      rating: 4.48,
      released: "2020-03-20",
      background_image: "https://placehold.co/600x800?text=DOOM+Eternal",
      genres: ["Shooter"],
      parent_platforms: ["PC", "PlayStation", "Xbox", "Switch"],
    },
    {
      id: 15,
      name: "Resident Evil 4 Remake",
      rating: 4.64,
      released: "2023-03-24",
      background_image: "https://placehold.co/600x800?text=RE4",
      genres: ["Horror"],
      parent_platforms: ["PC", "PlayStation", "Xbox"],
    },
    {
      id: 16,
      name: "Sekiro: Shadows Die Twice",
      rating: 4.58,
      released: "2019-03-22",
      background_image: "https://placehold.co/600x800?text=Sekiro",
      genres: ["Action"],
      parent_platforms: ["PC", "PlayStation", "Xbox"],
    },
    {
      id: 17,
      name: "Dark Souls III",
      rating: 4.56,
      released: "2016-03-24",
      background_image: "https://placehold.co/600x800?text=Dark+Souls+3",
      genres: ["RPG"],
      parent_platforms: ["PC", "PlayStation", "Xbox"],
    },
    {
      id: 18,
      name: "Bloodborne",
      rating: 4.74,
      released: "2015-03-24",
      background_image: "https://placehold.co/600x800?text=Bloodborne",
      genres: ["Action RPG"],
      parent_platforms: ["PlayStation"],
    },
    {
      id: 19,
      name: "Ghost of Tsushima",
      rating: 4.73,
      released: "2020-07-17",
      background_image: "https://placehold.co/600x800?text=Ghost+of+Tsushima",
      genres: ["Action"],
      parent_platforms: ["PlayStation", "PC"],
    },
    {
      id: 20,
      name: "Death Stranding",
      rating: 4.24,
      released: "2019-11-08",
      background_image: "https://placehold.co/600x800?text=Death+Stranding",
      genres: ["Adventure"],
      parent_platforms: ["PC", "PlayStation"],
    },
    ...Array.from({ length: 30 }, (_, i) => ({
      id: i + 21,
      name: `Mock Game ${i + 21}`,
      rating: Number((3.8 + (i % 10) * 0.1).toFixed(2)),
      released: `202${i % 5}-01-01`,
      background_image: `https://placehold.co/600x800?text=Game+${i + 21}`,
      genres: ["Action"],
      parent_platforms: ["PC", "PlayStation", "Xbox"],
    })),
  ],
};
